apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
  namespace: prod
  labels:
    role: api
    env: demo
spec:
  type: NodePort
  selector:
    role: api
  ports:
    - protocol: TCP
      port: 3333         # External port
      targetPort: 3333  # Container's port
      nodePort: 30010   # The port on the node (if not specified, Kubernetes will assign one)

